name: Test
on:
    pull_request:
        paths-ignore:
            - '**.md'
    push:
        branches: [main]
        tags: ['*']
        paths-ignore:
            - '**.md'

jobs:
    phpunit:
        name: PHPUnit
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4

            - name: Setup Node.js
              uses: actions/setup-node@v4
              with:
                  node-version: lts/*
                  cache: npm

            - name: Setup PHP
              uses: shivammathur/setup-php@v2
              with:
                  php-version: '8.2'

            - name: Install Node dependencies
              run: npm ci

            - name: Install Composer dependencies
              run: composer install --no-progress --no-interaction

            - name: Run PHPUnit
              run: npm run test:php

    release:
        name: Upload Release Asset
        needs: [phpunit]
        if: startsWith(github.ref, 'refs/tags/')
        runs-on: ubuntu-latest
        permissions:
            attestations: write
            id-token: write
            contents: write
        steps:
            - name: Checkout code
              uses: actions/checkout@v4

            - name: Get tag
              id: tag
              run: echo "tag=${GITHUB_REF#refs/tags/}" >> $GITHUB_OUTPUT

            - name: Build project
              run: git archive -o /tmp/${{ github.event.repository.name }}-${{ steps.tag.outputs.tag }}.zip --prefix=${{ github.event.repository.name }}/ ${{ steps.tag.outputs.tag }}

            - name: Create Release
              uses: softprops/action-gh-release@v2
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
              with:
                  files: /tmp/${{ github.event.repository.name }}-${{ steps.tag.outputs.tag }}.zip

            - name: Build provenance attestation
              uses: actions/attest-build-provenance@v2
              with:
                  subject-path: /tmp/${{ github.event.repository.name }}-${{ steps.tag.outputs.tag }}.zip
